description: A blog about databases, programming, and other interesting things.
url: http://ora600.ru
permalink: /posts/:title
markdown: PPV
paginate: 5
paginate_path: "notes/page:num"

#include: [".well-known"]
sass:
    sass_dir: _sass
    sourcemap: true

title: Ora600
author: Pavel Popov

collections:
  travels:
    output: true
    permalink: /awesome/:path/

